#ifndef MAPPING_KEYWORD_H

#define MAPPING_KEYWORD_H

#include <string>
#include <unordered_map>

namespace ycc {
enum keywords_mapping {
  ASM,
  WAGARNA,
  NEW,
  THIS,
  AUTO,
  ENUM,
  KWOPERATOR,
  THROW,
  MANTIQI,
  EXPLICIT,
  PRIVATE,
  TRUE,
  BREAK,
  EXPORT,
  PROTECTED,
  TRY,
  CASE,
  EXTERN,
  PUBLIC,
  TYPEDEF,
  CATCH,
  FALSE,
  REGISTER,
  TYPEID,
  HARF,
  ASHRIYA,
  TYPENAME,
  ADADI,
  CLASS,
  FOR,
  WAPAS,
  UNION,
  CONST,
  DOST,
  SHORT,
  UNSINGED,
  GOTO,
  SIGNED,
  USING,
  CONTINUE,
  AGAR,
  SIZEOF,
  VIRTUAL,
  DEFAULT,
  INLINE,
  STATIC,
  KHALI,
  DELETE,
  VOLATILE,
  DO,
  LONG,
  STRUCT,
  DOUBLE,
  MUTABLE,
  SWITCH,
  WHILE,
  NAMESPACE,
  TEMPLATE,
  MARQAZI,
  MATN,
  INPUT,
  OUTPUT,
};
const std::unordered_map<std::string, keywords_mapping> KEYWORDS_MAP = {
    {"asm", keywords_mapping::ASM},
    {"wagarna", keywords_mapping::WAGARNA},
    {"new", keywords_mapping::NEW},
    {"this", keywords_mapping::THIS},
    {"auto", keywords_mapping::AUTO},
    {"enum", keywords_mapping::ENUM},
    {"operator", keywords_mapping::KWOPERATOR},
    {"throw", keywords_mapping::THROW},
    {"mantiqi", keywords_mapping::MANTIQI},
    {"explicit", keywords_mapping::EXPLICIT},
    {"private", keywords_mapping::PRIVATE},
    {"true", keywords_mapping::TRUE},
    {"break", keywords_mapping::BREAK},
    {"export", keywords_mapping::EXPORT},
    {"protected", keywords_mapping::PROTECTED},
    {"try", keywords_mapping::TRY},
    {"case", keywords_mapping::CASE},
    {"extern", keywords_mapping::EXTERN},
    {"public", keywords_mapping::PUBLIC},
    {"typedef", keywords_mapping::TYPEDEF},
    {"catch", keywords_mapping::CATCH},
    {"false", keywords_mapping::FALSE},
    {"register", keywords_mapping::REGISTER},
    {"typeid", keywords_mapping::TYPEID},
    {"harf", keywords_mapping::HARF},
    {"ashriya", keywords_mapping::ASHRIYA},
    {"typename", keywords_mapping::TYPENAME},
    {"adadi", keywords_mapping::ADADI},
    {"class", keywords_mapping::CLASS},
    {"for", keywords_mapping::FOR},
    {"wapas", keywords_mapping::WAPAS},
    {"union", keywords_mapping::UNION},
    {"const", keywords_mapping::CONST},
    {"dost", keywords_mapping::DOST},
    {"short", keywords_mapping::SHORT},
    {"unsigned", keywords_mapping::UNSINGED},
    {"goto", keywords_mapping::GOTO},
    {"signed", keywords_mapping::SIGNED},
    {"using", keywords_mapping::USING},
    {"continue", keywords_mapping::CONTINUE},
    {"agar", keywords_mapping::AGAR},
    {"sizeof", keywords_mapping::SIZEOF},
    {"virtual", keywords_mapping::VIRTUAL},
    {"default", keywords_mapping::DEFAULT},
    {"inline", keywords_mapping::INLINE},
    {"static", keywords_mapping::STATIC},
    {"khali", keywords_mapping::KHALI},
    {"delete", keywords_mapping::DELETE},
    {"volatile", keywords_mapping::VOLATILE},
    {"do", keywords_mapping::DO},
    {"long", keywords_mapping::LONG},
    {"struct", keywords_mapping::STRUCT},
    {"double", keywords_mapping::DOUBLE},
    {"mutable", keywords_mapping::MUTABLE},
    {"switch", keywords_mapping::SWITCH},
    {"while", keywords_mapping::WHILE},
    {"namespace", keywords_mapping::NAMESPACE},
    {"template", keywords_mapping::TEMPLATE},
    {"marqazi", keywords_mapping::MARQAZI},
    {"matn", keywords_mapping::MATN},
    {"input", keywords_mapping::INPUT},
    {"output", keywords_mapping::OUTPUT},
};
} // namespace ycc
#endif /* MAPPING_KEYWORD_H */
